name: Tools

on:
  push:
    branches: [ master ]
    paths: 'tools/**'
  pull_request:
    branches: [ master ]
    paths: 'tools/**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: zip tools.zip tools
